package Trace.GreenDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import Trace.GreenDao.Note;
import Trace.GreenDao.heartrate;

import Trace.GreenDao.NoteDao;
import Trace.GreenDao.heartrateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig heartrateDaoConfig;

    private final NoteDao noteDao;
    private final heartrateDao heartrateDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        heartrateDaoConfig = daoConfigMap.get(heartrateDao.class).clone();
        heartrateDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        heartrateDao = new heartrateDao(heartrateDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(heartrate.class, heartrateDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        heartrateDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public heartrateDao getHeartrateDao() {
        return heartrateDao;
    }

}
